[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["EELSNMF*"]

[tool.setuptools_scm]
version_file = "EELSNMF/_version.py"

[project]
name = "EELSNMF"
dynamic = ["version"]
description = "A package for NMF analysis taylored to EELS data"
readme = "README.md"
authors = [{ name = "Pau Torruella", email = "pau.torruellabesa@epfl.ch" }]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "colorcet>=3.2.1",
    "exspy>=0.3.2",
    "hyperspy>=2.4.0",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pyeelsmodel>=1.0.6",
    "rosettasciio>=0.14.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "tqdm>=4.69.0",
]

[project.optional-dependencies]
gpu = ["cupy"]
EML = ["whittaker-eilers"]
torch = ["torch"]
all = ["EELSNMF[cupy]", "EELSNMF[EML]", "EELSNMF[torch]"]

[project.urls]
"Homepage" = "https://github.com/PauTorru/EELSNMF"

[project.license]
file = "LICENSE.txt"

[dependency-groups]
dev = ["ruff>=0.15.22"]

[tool.ruff.lint]
ignore = ["E711", "E712", "E741"]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
